version: '3'
services:
  vuejs:
    build: ./Parking
    ports:
      - '8080:8080'
    volumes:
      - './Parking:/data'
    environment:
      - 'VUE_APP_BACKEND_URL=http://localhost:3000/'
    restart: always
  nodejs:
    build: ./backend-api
    ports:
      - '3000:3000'
    volumes:
      - './backend-api:/data'
    depends_on:
      - mongo
    environment:
      - 'URL_SOCKET_IO_GET=http://localhost:8080/'
      - 'DATABASE_URL=mongo:27017'
    restart: always
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - './db:/data/db'
